require(peer)
require(doParallel)
require(foreach)

setwd("d:/result")
path <- "./sim-miss"
dir.create(path = path, showWarnings = FALSE, recursive = TRUE)

#' generate table for missing data simulation. Then tbale includes ErC, ErXC, FPR, FNR and time 
#' @param control a list consists simlation setting, which can be generated by sim.control() function 
#' @return \item{table}{including ErC, ErXC, FPR, FNR and time with l1 and l0 penalty.}
#' @export 
sim.miss <- function(control = sim.control()) {
  n <- control$n
  p <- control$p
  q <- control$q
  nrank <- control$nrank
  mrank <- control$mrank
  s <- control$s
  snr <- control$snr
  miss <- control$miss

  sim.data <- sim.setup(n, p, q, nrank, s, snr)
  X <- sim.data$X
  Y <- sim.data$Y
  U <- sim.data$U
  V <- sim.data$V
  d <- sim.data$d
  C <- sim.data$C

  erank <- est.rank(Y, 20)

  table <- data.frame()
  for (miss_rate in miss) {
    if (miss_rate != 0) {
      t.ind <- sample.int(n * q, size = miss_rate * n * q)
      y <- as.vector(sim.data$Y)
      y[t.ind] <- NA
      Y <- matrix(y, n, q)
    }
    peer.l1 <- data.frame(ErC = 0, ErXC = 0, FPR = 0, FNR = 0, time = 0, miss = miss_rate)

    # peer  
    fit <- peer(X, Y, nrank = erank, penalty = "l1")
    Chat <- fit$C
    Uhat <- fit$U
    Vhat <- fit$V
    dhat <- fit$d
    peer.l1$ErC <- est.err(C, Chat)
    peer.l1$ErXC <- pred.err(X, C, Chat)
    rate <- frate(U, Uhat, dhat)
    peer.l1$FPR <- rate$fprate
    peer.l1$FNR <- rate$fnrate
    peer.l1$time <- fit$time

    table <- rbind(table, peer.l1)
  }
  rownames(table) <- NULL
  return(table)
}

cl.num <- 1 
repetition <- 200

n.fix <- 100
q.fix <- 100 
r.fix <- 3 
s.fix <- 4

sink(paste0(path, "/log"))

cl <- makeCluster(cl.num)
registerDoParallel(cl)

for (snr in c(0.25,0.5)) {
  cat("Begin snr = ", snr, '\n')
  t <- Sys.time()
  for (p in c(200,400)) {
    # define simulation setup
    setting <- sim.control(n = n.fix, p = p, q = q.fix, nrank = r.fix, s = s.fix, snr = snr, miss = c(0, 0.05, 0.1, 0.15))

    table <- foreach(i = 1:repetition, .combine = 'rbind', .packages = c("peer")) %dopar% {
      sim.miss(control = setting)
    }
    
    filename <- paste0("./sim-miss/snr-", snr * 100, "-p-", p, ".Rdata")
    save(table, file = filename)
  }
  cat("snr =", snr , "is finished,", "elapsed time is", format(Sys.time() - t), '\n')
}

stopImplicitCluster()
stopCluster(cl)

sink()